---

all:
  children:
    samba:
      hosts:
        192.168.182.251
    nextcloud:
      hosts:
        192.168.182.249
    server1c:
      hosts:
        192.168.137.2    
    s1:
      hosts:
        192.168.137.31
