- name : "Install Node Exporter"
  hosts: all 
  become: yes
  vars:
    node_file: node_exporter-1.3.1.linux-amd64
  tasks: 
  - name: Find latest Node Exporter release
    uri:
      url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
      return_content: true
    register: node_exporter_release
  - name: Create User Node Exporter
    user:
      name: node_exporter
      create_home: no
      shell: /bin/false
  - name: Get Node Exporter download URL
    set_fact:
      dl_url: "{{ node_exporter_release.json.assets | selectattr('name', 'search', 'linux-amd64') | list }}"
  - name: Edit version Node Exporter 
    shell: echo "{{ dl_url[0].browser_download_url }}" | sed 's|.*node_exporter-||' | sed -r 's/.l.+//' 
    register: node_exporter_v 
  - name: Download and extract Node Exporter
    unarchive:
      src: "{{ dl_url[0].browser_download_url }}"
      dest: /usr/local/bin
      remote_src: yes
      creates: /usr/local/bin/node_exporter
      owner: node_exporter
  - name: Create node_exporter systemd service file
    template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
  - name: Start and Enabled Node Exporter
    systemd:
      name: node_exporter
      daemon_reload: yes
      state: started
      enabled: yes
  - name: Test Open Port
    wait_for: 
      port: 9100 
      timeout: 3
      state: started
