---
- name : "Create VM template"
  hosts: s2
  vars_files:
    - secret.yml
  tasks:
  - name: Cloning virtual machine from  
    proxmox_kvm:
       api_user : "{{ api_user }}"
       api_password: "{{ api_password }}"
       api_host : "{{ api_host }}"
       name : "{{ name_vm }}"
       node : 's2'
       clone: "{{ template_name }}"
  - name: Increasing disk if it is necessary
    become: yes
    shell: A=$(qm list |grep {{ name_vm }} | awk '{print $1}'); qm resize $A {{ default_disk }} +{{ size_disk }}G
    when: '"{{ size_disk }}" != "0"'
  - name: Waiting to apply cloud init changes in disk
    wait_for:
       timeout: 5 
  - name: Start VM 
    proxmox_kvm:
       api_user : "{{ api_user }}"
       api_password: "{{ api_password }}"
       api_host : "{{ api_host }}"
       name : "{{ name_vm }}"
       node : 's2'
       state : started
       timeout: 300
    when: '"{{ size_disk }}" != "0"'
